### PR TITLE
Fix lint issues and add license so CI builds.

### PR DESCRIPTION
**Pull request by kbsriram**

### CODE REVIEW

**Comment by dhalbert** [comment]
@kbsriram Please check the website link in your GitHub profile. It is not what you would want.

**Comment by kbsriram** [comment]
Thanks for the heads-up @dhalbert - much appreciated!

**Comment by dhalbert** [comment]
BTW, did you mean to close this? Maybe it was meant for your own repo?

**Comment by jepler** [comment]
The CI error says:
```
Warning, treated as error:
autodoc: failed to import module 'adafruit_pio_uart'; the following exception was raised:
No module named 'rp2pio'
```
The first fix to try for this kind of error building documentation is to edit docs/conf.pyand add the module(s) that could not be imported to the list of "autodoc_mock_imports". In this case, rp2pio. This will allow the documentation building process to pretend rp2pio is importable, but occasionally leads to further errors.

An example of this is: https://github.com/adafruit/Adafruit_CircuitPython_NeoPxl8/blob/main/docs/conf.py#L30

**Comment by kbsriram** [comment]
Thank you @dhalbert and @jepler ! I'd closed this thinking I'd do some research on the CI issue first, without adding review load on you folks. Thank you for the very helpful hints - I'll re-open and see if I can get a clean build :-)

**Review by FoamyGuy — APPROVED** [review]
I don't have much knowledge of PIO specifically, but I had a look through these changes. 

The fixes to lint and other pre-commit checks all look good to me at this point, and the behavior of the looks unchanged to me.

Thanks for working on this @kbsriram

**Pull request merged**
